spring:
    datasource:
      url: jdbc:mysql://localhost:3306/employee
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: admin
liquibase:
  change-log: classpath:db/changelog/db.changelog-master.xml
